In [7]:
import pandas as pd
df = pd.read_csv('../data/citibike_weather_daily.csv')
df.head()

,ride_date,num_rides,avg_duration_min,temp_f,max_temp_f,min_temp_f,wind_speed_knots,precip_in,day_of_week,month
0,2013-07-01,16650,16.31,74.8,78.1,73.4,7.8,0.00,Monday,7
1,2013-07-02,22745,15.97,76.1,82.9,73.0,8.0,0.73,Tuesday,7
2,2013-07-03,21864,16.24,78.5,84.9,73.9,8.8,0.06,Wednesday,7
3,2013-07-04,22326,21.22,82.0,91.0,73.9,8.6,0.96,Thursday,7
4,2013-07-05,21842,18.04,84.4,93.0,75.9,9.0,0.00,Friday,7

In [8]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1610 entries, 0 to 1609
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ride_date         1610 non-null   object
 1   num_rides         1610 non-null   int64
 2   avg_duration_min  1610 non-null   float64
 3   temp_f            1610 non-null   float64
 4   max_temp_f        1610 non-null   float64
 5   min_temp_f        1610 non-null   float64
 6   wind_speed_knots  1610 non-null   float64
 7   precip_in         1610 non-null   float64
 8   day_of_week       1610 non-null   object
 9   month             1610 non-null   int64
dtypes: float64(6), int64(2), object(2)
memory usage: 125.9+ KB

,num_rides,avg_duration_min,temp_f,max_temp_f,min_temp_f,wind_speed_knots,precip_in,month
count,1610.000000,1610.000000,1610.000000,1610.000000,1610.000000,1610.000000,1610.000000,1610.000000
mean,32986.783230,15.425584,57.368509,67.317081,49.295901,9.013913,0.178398,6.544099
std,16910.147968,3.652670,17.876211,18.349408,17.832318,3.241211,2.508762,3.323772
min,876.000000,9.500000,8.300000,18.000000,1.000000,2.300000,0.000000,1.000000
25%,20505.500000,13.112500,43.625000,53.700000,35.700000,6.700000,0.000000,4.000000
50%,32272.500000,14.860000,59.300000,70.000000,51.100000,8.500000,0.000000,7.000000
75%,42915.750000,17.120000,73.500000,82.900000,64.900000,10.800000,0.060000,9.000000
max,78458.000000,81.110000,92.500000,100.900000,82.900000,22.400000,99.990000,12.000000