In [61]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
df = pd.read_csv('../data/citibike_weather_daily.csv')

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1610 entries, 0 to 1609
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ride_date         1610 non-null   object
 1   num_rides         1610 non-null   int64
 2   avg_duration_min  1610 non-null   float64
 3   temp_f            1610 non-null   float64
 4   max_temp_f        1610 non-null   float64
 5   min_temp_f        1610 non-null   float64
 6   wind_speed_knots  1610 non-null   float64
 7   precip_in         1610 non-null   float64
 8   day_of_week       1610 non-null   object
 9   month             1610 non-null   int64
dtypes: float64(6), int64(2), object(2)
memory usage: 125.9+ KB

In [63]:
# C1
df['ride_date'] = pd.to_datetime(df['ride_date'])
print(df.dtypes)

ride_date           datetime64[ns]
num_rides                    int64
avg_duration_min           float64
temp_f                     float64
max_temp_f                 float64
min_temp_f                 float64
wind_speed_knots           float64
precip_in                  float64
day_of_week                 object
month                        int64
dtype: object

## C2

In [64]:
#C2
df['precip_in'].sort_values(ascending=False)

951     99.99
304      4.88
1396     2.79
1219     2.31
527      2.26
        ...
1014     0.00
260      0.00
8        0.00
5        0.00
259      0.00
Name: precip_in, Length: 1610, dtype: float64

In [65]:
df[df['precip_in'] == 99.99]

,ride_date,num_rides,avg_duration_min,temp_f,max_temp_f,min_temp_f,wind_speed_knots,precip_in,day_of_week,month
951,2016-02-11,18748,13.52,28.1,39.9,23.0,17.3,99.99,Thursday,2

In [66]:
df['precip_in'] = df['precip_in'].replace(99.99, pd.NA)
df['precip_in'].isna().sum()

np.int64(1)

In [67]:
df['precip_in'] = df['precip_in'].fillna(0)

/var/folders/39/d29jcb4j6r794j7wkqsq4_mr0000gn/T/ipykernel_8543/46812156.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['precip_in'] = df['precip_in'].fillna(0)

# Why Fill instead of dropping?

## C3

In [68]:
day_of_week_dummies = pd.get_dummies(df['day_of_week'], drop_first=True)
print(day_of_week_dummies)

      Monday  Saturday  Sunday  Thursday  Tuesday  Wednesday
0       True     False   False     False    False      False
1      False     False   False     False     True      False
2      False     False   False     False    False       True
3      False     False   False      True    False      False
4      False     False   False     False    False      False
...      ...       ...     ...       ...      ...        ...
1605   False     False    True     False    False      False
1606    True     False   False     False    False      False
1607   False     False   False     False     True      False
1608   False     False   False     False    False       True
1609   False     False   False      True    False      False

[1610 rows x 6 columns]

## Reason for drop_first
I decided to use the drop_first because it prevents multicollinearity. Which would cause problems down the line during the model creation.

In [69]:
df = pd.concat([df, day_of_week_dummies], axis=1)

In [70]:
print(day_of_week_dummies.columns.tolist())
df.head()

['Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday']

,ride_date,num_rides,avg_duration_min,temp_f,max_temp_f,min_temp_f,wind_speed_knots,precip_in,day_of_week,month,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday
0,2013-07-01,16650,16.31,74.8,78.1,73.4,7.8,0.00,Monday,7,True,False,False,False,False,False
1,2013-07-02,22745,15.97,76.1,82.9,73.0,8.0,0.73,Tuesday,7,False,False,False,False,True,False
2,2013-07-03,21864,16.24,78.5,84.9,73.9,8.8,0.06,Wednesday,7,False,False,False,False,False,True
3,2013-07-04,22326,21.22,82.0,91.0,73.9,8.6,0.96,Thursday,7,False,False,False,True,False,False
4,2013-07-05,21842,18.04,84.4,93.0,75.9,9.0,0.00,Friday,7,False,False,False,False,False,False